create extension if not exists pgcrypto;

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text,
  price text not null,
  location text not null,
  type text not null,
  bedrooms integer,
  bathrooms integer,
  area text,
  amenities text[] default '{}',
  images text[] default '{}',
  videos text[] default '{}',
  featured boolean default false,
  status text not null default 'draft' check (status in ('draft', 'published')),
  created_at timestamptz not null default now()
  ,contact_phone text
  ,contact_email text
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text,
  message text,
  property_id bigint references public.properties(id) on delete set null,
  status text not null default 'new' check (status in ('new', 'contacted', 'closed')),
  created_at timestamptz not null default now()
);

create table if not exists public.lead_rate_limits (
  ip text primary key,
  window_started_at timestamptz not null default now(),
  submission_count integer not null default 0 check (submission_count >= 0)
);

create table if not exists public.settings (
  id integer primary key default 1 check (id = 1),
  company_name text not null default 'Mudigere Properties',
  phone text not null default '+91 99721 94722',
  email text not null default 'hello@mudigereproperties.com',
  banner_image text,
  logo_image text,
  footer_logo_image text,
  founder_image text,
  home_banner_image text,
  about_banner_image text,
  properties_banner_image text,
  cta_banner_image text,
  home_about_image text,
  social_links jsonb not null default '{"instagram":"","facebook":"","linkedin":""}'::jsonb
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'role' = 'admin', false);
$$;

create or replace function public.allow_lead_submission(request_ip text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  permitted boolean;
begin
  insert into public.lead_rate_limits (ip, window_started_at, submission_count)
  values (request_ip, now(), 1)
  on conflict (ip) do update set
    window_started_at = case
      when public.lead_rate_limits.window_started_at < now() - interval '1 hour' then now()
      else public.lead_rate_limits.window_started_at
    end,
    submission_count = case
      when public.lead_rate_limits.window_started_at < now() - interval '1 hour' then 1
      else public.lead_rate_limits.submission_count + 1
    end
  returning submission_count <= 5 into permitted;

  return permitted;
end;
$$;

insert into public.settings (id)
values (1)
on conflict (id) do nothing;

alter table public.properties enable row level security;
alter table public.leads enable row level security;
alter table public.lead_rate_limits enable row level security;
alter table public.settings enable row level security;

drop policy if exists "Published properties are public" on public.properties;
create policy "Published properties are public"
on public.properties for select
using (status = 'published');

drop policy if exists "Authenticated users manage properties" on public.properties;
drop policy if exists "Admins manage properties" on public.properties;
create policy "Admins manage properties"
on public.properties for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Authenticated users manage leads" on public.leads;
drop policy if exists "Admins manage leads" on public.leads;
create policy "Admins manage leads"
on public.leads for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

revoke all on function public.allow_lead_submission(text) from public;
grant execute on function public.allow_lead_submission(text) to service_role;

drop policy if exists "Settings are public" on public.settings;
create policy "Settings are public"
on public.settings for select
using (true);

drop policy if exists "Authenticated users manage settings" on public.settings;
drop policy if exists "Anyone can manage settings" on public.settings;
drop policy if exists "Admins manage settings" on public.settings;
create policy "Admins manage settings"
on public.settings for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into storage.buckets (id, name, public)
values ('property-media', 'property-media', true)
on conflict (id) do update set public = true;

drop policy if exists "Property media is public" on storage.objects;
create policy "Property media is public"
on storage.objects for select
using (bucket_id = 'property-media');

drop policy if exists "Authenticated users upload property media" on storage.objects;
drop policy if exists "Authenticated users update property media" on storage.objects;
drop policy if exists "Authenticated users delete property media" on storage.objects;
drop policy if exists "Admins manage property media" on storage.objects;
create policy "Admins manage property media"
on storage.objects for all
to authenticated
using (bucket_id = 'property-media' and public.is_admin())
with check (bucket_id = 'property-media' and public.is_admin());
